#!/bin/bash

##
# Make CSV report of multiple git repos in the same root folder
#

REPORT="./reporeport.csv"
ROWS=""
echo -e "REPO\tCOMMIT\tCOMMITTER\tCOMMITER EMAIL\tDATE\tMESSAGE\tREPO" >$REPORT;
for repo in *;
    do 
    URL=$(echo "https://github.com/$(git -C ./$repo/ config --get remote.origin.url | awk -F: '{print $2}')")
    git -C ./$repo/ log -1 --no-merges --author='^(?!github-classroom\[bot\]).*$' --grep='GitHub Classroom' --invert-grep --perl-regexp --pretty=format:"$repo%x09%h%x09%cn%x09%ce%x09%cs%x09%f%x09=HYPERLINK(\"$URL\";\"$repo\")%n"  >> $REPORT
done;
cat $REPORT
echo "Saved to $REPORT"
echo "HINT: for repo in *; do git -C ./\$repo/ pull; done"
