#!/bin/sh
#
# Usage (single file): sftp_put /payload/dir/file.txt user@sftp.server.com remote_directory
# Usage (extension wildcard): sftp_put "/payload/dir/*.txt" user@sftp.server.com remote_directory
# N.B. A wildcard path must be quoted and only extension wildcards are supported (*, *.* or file* won't work)

if [ $# -ne 3 ]
then
        echo "USAGE: sftp_put { /dir/file.txt | \"/dir/*.txt\" } user@sftp.server.com remote_directory"
        exit
fi

payload=$1
server_string=$2
host_dir=$3
local_dir=$(dirname "${payload}")
local_file=$(basename "${payload}")

echo cd $host_dir > /tmp/sftp_batch.tmp
echo lcd $local_dir >> /tmp/sftp_batch.tmp
echo mput $local_file >> /tmp/sftp_batch.tmp
echo quit >> /tmp/sftp_batch.tmp

/usr/bin/sftp -b /tmp/sftp_batch.tmp $server_string 1> /dev/null

rm /tmp/sftp_batch.tmp

